apiVersion: batch/v1
kind: CronJob
metadata:
  name: mk-time-printer
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mk-time
            image: busybox
            args:
            - /bin/sh
            - -c
            - date
          restartPolicy: OnFailure
