prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: default
          resources:
            requests:
              storage: 3Gi

grafana:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClassName: default
